// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACpnTP4orMdMnT9dEcS5PqBh_UoXiLQeQ',
    appId: '1:303749935479:web:945909dfe61de5f6a93172',
    messagingSenderId: '303749935479',
    projectId: 'van-view-3c2dc',
    authDomain: 'van-view-3c2dc.firebaseapp.com',
    storageBucket: 'van-view-3c2dc.firebasestorage.app',
    measurementId: 'G-E2N39Q7D9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv0Zju3LlSp3b6C2B9V7bPvK9JUwbjP6k',
    appId: '1:303749935479:android:194cb612c5a97e54a93172',
    messagingSenderId: '303749935479',
    projectId: 'van-view-3c2dc',
    storageBucket: 'van-view-3c2dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaiJiDbh8SDk4rjHNQilU-C7A0zntVmwk',
    appId: '1:303749935479:ios:825a246348e5c1cba93172',
    messagingSenderId: '303749935479',
    projectId: 'van-view-3c2dc',
    storageBucket: 'van-view-3c2dc.firebasestorage.app',
    iosBundleId: 'com.example.vanViewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaiJiDbh8SDk4rjHNQilU-C7A0zntVmwk',
    appId: '1:303749935479:ios:825a246348e5c1cba93172',
    messagingSenderId: '303749935479',
    projectId: 'van-view-3c2dc',
    storageBucket: 'van-view-3c2dc.firebasestorage.app',
    iosBundleId: 'com.example.vanViewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACpnTP4orMdMnT9dEcS5PqBh_UoXiLQeQ',
    appId: '1:303749935479:web:5037fb7b0a07e672a93172',
    messagingSenderId: '303749935479',
    projectId: 'van-view-3c2dc',
    authDomain: 'van-view-3c2dc.firebaseapp.com',
    storageBucket: 'van-view-3c2dc.firebasestorage.app',
    measurementId: 'G-JCDLHYDLJH',
  );
}
